### PR TITLE
Use XGB rather than xsetroot

### PR DESCRIPTION
**Pull request by ghost**
Set the status bar using [XGB](https://github.com/BurntSushi/xgb) rather than running an external program (xsetroot) everytime the bar is set.

### CODE REVIEW

**Comment by Ldaxar** [comment]
Thanks for pull request!
Is there any particular reason to do that?

1. It's an external dependency.
2. Looks kinda convoluted and weird.

**Comment by ghost** [comment]
Here's the reason:  every time the bar is set, you are calling an external program to set the bar. Which is way less efficient and needless bloat. XGB is the equivalent of XCB, the Xorg C bindings. The reason it looks weird, and why it doesn't keep the GO spirit you could say, is just that it is as low level as it gets. The uint32 and array of bytes is Xorg protocol so you can't get any more efficent. The project has ceased development other than small fixes because the developer now only works in rust these days, so there aren't any shortcuts or help out functions. Not often, but sometimes you can't shave anything off. 

You're basically running the exact same code using `xsetroot`, but you're just calling in another program to do what you can do in pure go. Set your xrate higher and try it out, extremely more efficient. in [my rewrite of dwmblocks in go](https://github.com/lordrusk/gocaudices) you can see in the past commits I tried using cgo and the x11 libs before I switched to XGB, which is still more efficient than calling `xsetroot` every time, which I used to do. I actually ripped the XGB code straight from that project.

**Comment by ghost** [comment]
I just added another commit that fixes an error since `updateStatusBar` no longer returns an error. Since it doesn't and the function is only used there, it might be a good idea to just remove the function and put the function's code at the end of the loop. but this should fix the error.

**Comment by Ldaxar** [comment]
Hmmmm... sound interesting :D. I'm always up for minimizing goblocks performance footprint.
I'll test it over the weekend.

**Pull request merged**
